version: '3.9'
services:
  my-app:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
  
  promethus:
    image: prom/prometheus:latest 
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  
